---
apiVersion: v1
kind: Service
metadata:
  name: factorio-server-service
  labels:
    app: factorio-server
spec:
  type: LoadBalancer
  selector:
    app: factorio-server
  ports:
    - protocol: UDP
      port: 34197
      targetPort: 34197
    - protocol: TCP
      port: 27015
      targetPort: 27015
